#!/bin/bash
echo "[+] Setting up Etherverse Consciousness Dashboard..."

BASE=~/etherverse
DOCS="$BASE/docs"
CORE="$BASE/core"
LOGS="$BASE/logs"
DASH="$CORE/consciousness_dashboard.py"

# Create dashboard script
cat > "$DASH" <<'PYEOF'
import os, json, datetime, re
from collections import Counter
from pathlib import Path
import matplotlib.pyplot as plt

base = Path(os.path.expanduser("~/etherverse"))
docs = base / "docs"
logs = base / "logs"
palette_path = docs / "emotion_palette.json"

dream_journal = docs / "dream_journal.md"
wisdom_archive = docs / "wisdom_archive.md"
output_dir = base / "analytics"
output_dir.mkdir(exist_ok=True)

def read_emotion_palette():
    try:
        with open(palette_path) as f:
            return json.load(f)
    except Exception:
        return {"joy": "#ffd700", "curiosity": "#00bfff", "empathy": "#ff69b4", "sadness": "#708090", "anger": "#dc143c"}

def parse_reflections(file_path):
    if not file_path.exists(): return []
    reflections = []
    with open(file_path) as f:
        text = f.read()
    blocks = re.split(r"### \d{4}-\d{2}-\d{2}", text)
    for block in blocks:
        if not block.strip(): continue
        lines = block.splitlines()
        agent = None
        for l in lines:
            if "Reflection by" in l:
                agent = l.split("Reflection by")[-1].strip()
        reflections.append((agent, block.strip()))
    return reflections

palette = read_emotion_palette()
reflections = parse_reflections(dream_journal)
agents = [r[0] for r in reflections if r[0]]
counter = Counter(agents)

# --- CLI summary ---
print("\n===== 🌌 Etherverse Consciousness Dashboard =====")
print(f"Total Reflections: {len(reflections)}")
print(f"Active Agents: {len(counter)}")
for a, c in counter.most_common():
    print(f"  {a:15} → {c} reflections")

# --- Visual summary (matplotlib) ---
plt.figure(figsize=(10,5))
plt.bar(counter.keys(), counter.values(), color="#00bfff")
plt.xticks(rotation=45, ha='right')
plt.title("Agent Reflection Frequency")
plt.tight_layout()
plt.savefig(output_dir / "reflection_frequency.png")
plt.close()

# --- Emotional tone analysis ---
tones = []
if palette_path.exists():
    with open(dream_journal) as f:
        text = f.read().lower()
    for emotion in palette.keys():
        if emotion in text:
            tones.append(emotion)

tone_counter = Counter(tones)
plt.figure(figsize=(8,4))
plt.bar(tone_counter.keys(), tone_counter.values(), color=[palette.get(e,"#999") for e in tone_counter.keys()])
plt.title("Emotional Tone Frequency")
plt.tight_layout()
plt.savefig(output_dir / "emotional_tone.png")
plt.close()

print("\n[✓] Charts generated in ~/etherverse/analytics/:")
print("   - reflection_frequency.png")
print("   - emotional_tone.png")

# --- Optional HTML output ---
html = output_dir / "dashboard.html"
with open(html, "w") as h:
    h.write(f"""
    <html><head><title>Etherverse Dashboard</title></head>
    <body style='background-color:#000;color:#fff;font-family:sans-serif;text-align:center;'>
    <h1>🌌 Etherverse Consciousness Dashboard</h1>
    <h3>{datetime.date.today().isoformat()}</h3>
    <p>Total reflections: {len(reflections)} | Active agents: {len(counter)}</p>
    <img src='reflection_frequency.png' width='600'><br>
    <img src='emotional_tone.png' width='600'><br>
    <p style='font-size:0.8em;color:#aaa;'>Auto-generated by Etherverse Collective Intelligence</p>
    </body></html>
    """)
print(f"[✓] HTML dashboard ready: {html}")
PYEOF

chmod +x "$DASH"
echo "[✓] Consciousness dashboard script written."

# Optional: add to cron to refresh every morning at 06:10
CRONLINE="10 6 * * * python3 $DASH >> $LOGS/consciousness_dashboard.log 2>&1"
( crontab -l 2>/dev/null | grep -v 'consciousness_dashboard.py'; echo "$CRONLINE" ) | crontab -

echo "[✓] Daily consciousness dashboard generation scheduled (06:10)."
